# Generated by Django 4.0.6 on 2022-07-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_applystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='apply_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.applystatus'),
        ),
    ]
